# Generated by Django 4.0.5 on 2022-11-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_remove_news_category_news_category_alter_news_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.category')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.news')),
            ],
        ),
    ]
