# Generated by Django 4.0.5 on 2022-11-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_newscategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(through='News.NewsCategory', to='News.category'),
        ),
    ]
