# Generated by Django 4.0.5 on 2022-08-31 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_comment_delete_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
