# Generated by Django 4.0.5 on 2022-09-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0008_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ads.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ads.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ads.ad'),
        ),
    ]
