# Generated by Django 4.0.5 on 2022-09-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0009_alter_ad_category_alter_ad_game_alter_comment_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Видимость статьи'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ads.ad', verbose_name='Объявление'),
        ),
    ]
