# Generated by Django 4.0.5 on 2022-10-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0010_comment_active_alter_comment_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to='Ads.users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to='Ads.users'),
        ),
    ]
