# Generated by Django 4.0.5 on 2022-10-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0011_comment_dislike_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='comment_dislikes', to='Ads.users'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to='Ads.users'),
        ),
    ]
